import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import "@mysten/dapp-kit/dist/index.css";
import Provider from "./provider";
import { VStack } from "@chakra-ui/react";
import { Header } from "./_components/Header";

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className}`}>
        <Provider>
          <VStack w={"full"} h={"100vh"}>
            <Header />
            {children}
          </VStack>
        </Provider>
      </body>
    </html>
  );
}
